CC = /usr/bin/gcc
CFLAGS = -Wall -pedantic -Wextra -ansi -O0 -g

BUILD = ./build

virtual:
	$(CC) -o $(BUILD)/malloc_ex1 $(CFLAGS) malloc_ex1.c
	$(CC) -o $(BUILD)/null_deref $(CFLAGS) null_deref.c

scratch:
	$(CC) -o $(BUILD)/scratch $(CFLAGS) scratch.c

